# Generated by Django 2.2.3 on 2019-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govtrack', '0005_auto_20190719_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetype',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodetype',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
