# Generated by Django 2.2.4 on 2019-08-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("govtrack", "0015_auto_20190813_1342"),
    ]

    operations = [
        migrations.RenameModel(old_name="Node", new_name="Area",),
        migrations.AlterField(
            model_name="declaration", name="node", field=models.IntegerField(),
        ),
    ]
