# Generated by Django 2.2.4 on 2019-08-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("govtrack", "0016_auto_20190813_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaration",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="govtrack.Area"
            ),
        ),
    ]
