# Generated by Django 2.2.4 on 2019-08-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govtrack', '0017_auto_20190813_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='node',
            new_name='area',
        ),
    ]
