# Generated by Django 2.2.4 on 2019-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govtrack', '0018_auto_20190813_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='key_contact',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
