# Generated by Django 2.2.5 on 2019-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govtrack', '0022_auto_20191011_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='proxied_areas',
            field=models.ManyToManyField(blank=True, related_name='proxy_declarations', to='govtrack.Area'),
        ),
    ]
