# Generated by Django 2.2.6 on 2020-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govtrack', '0022_auto_20191011_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='agglomeration',
            field=models.BooleanField(default=False),
        ),
    ]
