# Generated by Django 2.2.5 on 2020-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("govtrack", "0023_area_agglomeration"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="popcount_ready",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="country",
            name="popcount_since",
            field=models.DateField(blank=True, null=True),
        ),
    ]
