# Generated by Django 2.2.9 on 2020-01-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("govtrack", "0024_auto_20200123_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="current_popcount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
