# Generated by Django 2.2.3 on 2019-07-21 04:14

from django.db import migrations, models
import django.db.models.deletion
import django_dag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcreteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('children', models.ManyToManyField(blank=True, related_name='_parents', through='dag.ConcreteEdge', to='dag.ConcreteNode')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django_dag.models.NodeBase),
        ),
        migrations.AddField(
            model_name='concreteedge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConcreteNode_parent', to='dag.ConcreteNode'),
        ),
        migrations.AddField(
            model_name='concreteedge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConcreteNode_child', to='dag.ConcreteNode'),
        ),
    ]
